### ISSUE TITLE
[EVNNPC] Lỗi 204: không kết nối được đến máy chủ EVN

### ISSUE THREAD

**Issue by dungvq3** [trvqhuy/ha-evn#9]
![132537EA-7C30-421E-9068-97E54D92ADC7](https://user-images.githubusercontent.com/66892022/193280439-269038ac-c8c3-4611-8649-8e7f06e8c087.png)

* đang dùng binh thường tự nhiên 3 hôm nay lỗi không xác định, gỡ ra cài lại cũng không được.
* nhờ tác giả xem lại giúp, log như trên.
* Tks!

**Comment by trvqhuy** [comment]
Chào @dungvq3, 

Đây không phải lỗi từ phía của công cụ `nestup_evn` (EVN Data Fetcher)

Nguyên nhân là do hiện tại máy chủ EVNNPC đang bảo trì, nên công cụ không thể kết nối để lấy dữ liệu.
Bạn có thể kiểm tra bằng cách vào App **EVNNPC**, phần `Tra cứu` > `Tra cứu sản lượng theo ngày`, bạn sẽ thấy App không thể load được dữ liệu mới.

**Comment by dungvq3** [comment]
Mình vào hiện tại vẫn tra được 
![F3BF4A3F-4B1B-4EEF-9424-8F953B1A78DB](https://user-images.githubusercontent.com/66892022/193395971-b9d45ecb-071b-4d69-a660-40b665fb3a96.png)

**Comment by trvqhuy** [comment]
> Bạn có thể kiểm tra bằng cách vào App **EVNNPC** (Android hoặc IOS), phần `Tra cứu` > `Sản lượng điện tiêu thụ`, bạn sẽ thấy App không thể load được dữ liệu mới.

Ở trên bạn đã kiểm tra thông qua Website trên điện thoại, bạn kiểm tra lại bằng App của EVN (tải về từ App Store hoặc Play Store) giúp mình nhé. 

Lí do là vì API dữ liệu mình lấy từ App chứ không phải Website.
